/*
 *********************************************************************************
 *     Copyright (c) 2010   ASIX Electronic Corporation      All rights reserved.
 *
 *     This is unpublished proprietary source code of ASIX Electronic Corporation
 *
 *     The copyright notice above does not evidence any actual or intended
 *     publication of such source code.
 *********************************************************************************
 */
/*================================================================================
 * Module Name : hsuart.h
 * Purpose     : A header file of UART2 & UART3 module.
 *               It defines all High-Speed UART registers.
 * Author      : Robin Lee
 * Date        : 
 * Notes       :
 *================================================================================
 */
#ifndef HSUART_H
#define HSUART_H

/* NAMING CONSTANT DECLARATIONS */


/* INCLUDE SPECIFICATIONS DECLARATIONS */


/* HSUART Controller Register Map */
#define	HSRBR		0x00		// Receiver Buffer Register: Receiver FIFO output.
#define HSTHR		0x00        // Transmitter Holding Register: Transmit FIFO input.
#define	HSDLLR		0x00        // Divisor Latch Low Register.
#define	HSIER		0x01		// Interrupt Enable Register: Enable/Mask Interrupts generated by UART.
#define	HSDLHR		0x01        // Divisor Latch High Register.
#define	HSIIR		0x02		// Interrupt Identification Register: Get interrupt information.
#define	HSFCR		0x02        // FIFO Control Register: Control FIFO options.
#define	HSLCR		0x03		// Line Control Register: Control connection.
#define	HSMCR		0x04        // Modem Control Register: Control modem.
#define	HSLSR		0x05        // Line Status Register: Status information.
#define	HSMSR		0x06        // Modem Status Register: Modem Status.
#define	HSDPR		0x07        // Divisor Parameter Register.
#define	HSAFCSR		0x08        // Auto Flow Control Setting Register.
#define	HSXONR		0x09        // XON Register.
#define	HSXOFFR		0x0b        // XOFF Register.
#define	HSECR		0x0d        // Escape Character Register.
#define	HSSFCGR		0x0f		// Software Floe Control Gap Register.

#define	HSDCR		0x10        // DMA Control Register.
#define	HSDIER		0x11        // DMA Interrupt Enable Register.
#define	HSDSR		0x12        // DMA Status Register.
#define	HSTDAR		0x13        // Transmit DMA Address Register.
#define	HSTDBCR		0x16        // Transmit DMA Byte Count Register.
#define	HSRBSP		0x18        // Receive Buffer Ring Start Pointer.
#define	HSRBEP		0x1a        // Receive Buffer Ring End Pointer.
#define	HSRBWP		0x1c        // Receive Buffer Ring Write Pointer.
#define	HSRBRP		0x1e        // Receive Buffer Ring Read Pointer.
#define	HSRBABC		0x20        // Receive Buffer Ring Available Byte Count.
#define	HSRBOTL		0x22        // Receive Buffer Ring Occupancy Trigger Level.
#define	HSRBDEP		0x24        // Receive Buffer Ring Data Error Pointer.
#define	HSRBRTG		0x26        // Receive Buffer Ring Timeout Gap.
                                
/* HSIER 0x01 */
#define	HSIER_RDI_ENB		BIT0
#define	HSIER_RDI_DISB		0
#define	HSIER_TFEI_ENB		BIT1
#define	HSIER_TFEI_DISB		0
#define	HSIER_RLSI_ENB		BIT2
#define	HSIER_RLSI_DISB		0
#define	HSIER_MSI_ENB		BIT3
#define	HSIER_MSI_DISB		0
#define	HSIER_TDCI_ENB		BIT4
#define	HSIER_TDCI_DISB		0
#define	HSIER_RBRFI_ENB		BIT5
#define	HSIER_DOEI_ENB		BIT6
#define	HSIER_FCCRI_ENB		BIT7

/* HSIIR 0x02 */
#define	HSIIR_NONE_INTR		0x01
#define	HSIIR_RLS_INTR		0x06
#define	HSIIR_DMAS_INTR		0x10
#define	HSIIR_RD_TRIG_INTR	0x04
#define	HSIIR_RD_TI_INTR	0x0C
#define	HSIIR_TFE_INTR		0x02
#define	HSIIR_MS_INTR		0x00

/* HSFCR 0x02 */
#define HSFCR_FIFOE			BIT0
#define HSFCR_RFR			BIT1
#define HSFCR_TFR			BIT2
#define	HSFCR_RSTOP			BIT3
#define	HSFCR_HSUART_ENB	BIT4
#define HSFCR_TRIG_01		0
#define HSFCR_TRIG_04		BIT6
#define HSFCR_TRIG_08		BIT7
#define HSFCR_TRIG_14		BIT6+BIT7

/* HSLCR 0x03 */
#define HSLCR_CHAR_5		0
#define HSLCR_CHAR_6		BIT0
#define HSLCR_CHAR_7		BIT1
#define HSLCR_CHAR_8		BIT1+BIT0
#define HSLCR_STOP_15		BIT2
#define HSLCR_STOP_10		0
#define HSLCR_PE_ENB		BIT3
#define HSLCR_PE_DISB		0
#define HSLCR_EPS_EVEN		BIT4
#define HSLCR_EPS_ODD		0
#define HSLCR_SPB_ENB		BIT5
#define HSLCR_SPB_DISB		0
#define HSLCR_BCB_ENB		BIT6
#define HSLCR_BCB_DISB		0
#define HSLCR_DLAB_ENB		BIT7

/* HSMCR 0x04 */
#define HSMCR_DTR			BIT0
#define HSMCR_RTS			BIT1
#define HSMCR_OUT1			BIT2
#define HSMCR_OUT2			BIT3
#define HSMCR_LOOPB			BIT4
#define	HSMCR_DEREC_SLEEP	0
#define	HSMCR_DEREC_STPHD	BIT6
#define	HSMCR_DEREC_SLAVE	BIT7
#define	HSMCR_DEREC_MASTER	BIT7|BIT6

/* HSLSR 0x05 */
#define HSLSR_DR_DATA		BIT0
#define HSLSR_DR_EMPTY		0
#define HSLSR_OE_OVER		BIT1
#define HSLSR_OE_NORMAL		0
#define HSLSR_PE_ERROR		BIT2
#define HSLSR_PE_NORMAL		0
#define HSLSR_FE_ERROR		BIT3
#define HSLSR_FE_NORMAL		0
#define HSLSR_BI_INT		BIT4
#define HSLSR_BI_NORMAL		0
#define HSLSR_TFIFO_EMPTY	BIT5
#define HSLSR_TFIFO_NORMAL	0
#define HSLSR_TSMR_EMPTY	BIT6
#define HSLSR_TSMR_NORMAL	0
#define HSLSR_FERR_ERROR	BIT7
#define HSLSR_FERR_NORMAL	0

/* HSMSR 0x06 */
#define HSMSR_DCTS			BIT0
#define HSMSR_DDSR			BIT1
#define HSMSR_TERI			BIT2
#define HSMSR_DDCD			BIT3
#define HSMSR_CTS			BIT4
#define HSMSR_DSR			BIT5
#define HSMSR_RI			BIT6
#define HSMSR_DCD			BIT7

/* HSAFCSR 0x08 */
#define HSAFCSR_ACTSE_ENB	BIT0
#define HSAFCSR_ARTSE_ENB	BIT1
#define HSAFCSR_ASFCE_ENB	BIT2
#define HSAFCSR_DCSE_ENB	BIT3
#define HSAFCSR_AECE_ENB	BIT4
#define HSAFCSR_DECE_ENB	BIT5
#define HSAFCSR_SXON		BIT6
#define HSAFCSR_SXOFF		BIT7

/* HSUART DMA Register */
/* HSDCR 0x10 */
#define HSDCR_STD			BIT0
#define	HSDCR_PXCTT			BIT1
#define	HSDCR_WE			BIT3
#define HSDCR_RBRE_ENB		BIT4
#define HSDCR_RBRE_DISB		0
#define HSDCR_RDECE_ENB		BIT5
#define HSDCR_RDECE_DISB	0
#define HSDCR_RDEFE_ENB		BIT6
#define HSDCR_RDEFE_DISB	0
#define	HSDCR_PRERF			BIT7

/* HSDSR 0x12 */
#define HSDSR_TDC_CPL		BIT0
#define HSDSR_XCFTL			BIT1
#define	HSDSR_RBTDE			BIT2
#define	HSDSR_WAKE_UP		BIT3
#define	HSDSR_RBRF			BIT4
#define HSDSR_ECRRT			BIT5
#define HSDSR_FCCR			BIT6
#define HSDSR_FCCRS			BIT7

/* HSuart Action Flag */
#define HSDMA_INT			BIT0
#define HSDMA_GO			BIT1
#define HSDMA_KEEPGO		BIT2
#define HSDMA_RX_CPL		BIT3
#define HSDMA_TX_CPL		BIT4
#define HS_WAKEUP_REQ		BIT5

/* HSUART Baud Rate definition */
#define	HS_BR40M_921600			0x0001
#define	HS_BR40M_115200			0x0008
#define	HS_BR40M_57600			0x0010
#define	HS_BR40M_38400			0x0018
#define	HS_BR40M_19200			0x0030
#define	HS_BR40M_9600			0x0061
#define	HS_BR40M_7200			0x0081
#define	HS_BR40M_4800			0x00c2
#define	HS_BR40M_3600			0x0102
#define	HS_BR40M_2400			0x0184
#define	HS_BR40M_1200			0x0307

#define	HS_BR80M_921600			0x0002
#define	HS_BR80M_115200			0x0010
#define	HS_BR80M_57600			0x0020
#define	HS_BR80M_38400			0x0030
#define	HS_BR80M_19200			0x0061
#define	HS_BR80M_9600			0x00C2
#define	HS_BR80M_7200			0x0102
#define	HS_BR80M_4800			0x0184
#define	HS_BR80M_3600			0x0205
#define	HS_BR80M_2400			0x0307
#define	HS_BR80M_1200			0x060E


#endif /* End of HSUART_H */
